ALTER TABLE tenant ADD COLUMN IF NOT EXISTS color_primario VARCHAR(7) NOT NULL DEFAULT '#b5007d';
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS titulo_pagina VARCHAR(120);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS meta_pixel_id VARCHAR(50);
